/*
股票代码信息表(其余信息后续追加)
 */
drop table IF EXISTS T_STOCK_INFO;
CREATE TABLE T_STOCK_INFO(
  stock_id varchar(10) PRIMARY KEY ,
  stock_name VARCHAR(20)
);

COMMENT ON TABLE T_STOCK_INFO IS '股票id表';
COMMENT ON COLUMN T_STOCK_INFO.stock_id IS '股票代码';
COMMENT ON COLUMN T_STOCK_INFO.stock_name IS '股票名称';

/*
股票价格表(其余信息后续追加)
 */
drop table IF EXISTS T_STOCK_TRAINNING_INFO;
CREATE TABLE T_STOCK_TRAINNING_INFO(
  stock_id varchar(10),
  s_date varchar(8),
  open_price NUMERIC(9,3),
  close_price NUMERIC(9,3),
  max_price NUMERIC(9,3),
  min_price NUMERIC(9,3),
  PRIMARY KEY (stock_id,s_date)
);

COMMENT ON TABLE T_STOCK_TRAINNING_INFO IS '股票价格明细表';
COMMENT ON COLUMN T_STOCK_TRAINNING_INFO.stock_id IS '股票代码';
COMMENT ON COLUMN T_STOCK_TRAINNING_INFO.s_date IS '数据日期';
COMMENT ON COLUMN T_STOCK_TRAINNING_INFO.open_price IS '开盘价格';
COMMENT ON COLUMN T_STOCK_TRAINNING_INFO.close_price IS '关盘价格';
COMMENT ON COLUMN T_STOCK_TRAINNING_INFO.max_price IS '当天最高价';
COMMENT ON COLUMN T_STOCK_TRAINNING_INFO.min_price IS '当天对低价';

drop table IF EXISTS T_STOCK_SYS_PARAM;
CREATE TABLE T_STOCK_SYS_PARAM(
  PARAM_ID NUMERIC(6) PRIMARY KEY ,
  PARAM_NAME VARCHAR(20),
  PARAM_VALUE VARCHAR(20)
);

COMMENT ON TABLE T_STOCK_SYS_PARAM IS '股票分析系统参数表';
COMMENT ON COLUMN T_STOCK_SYS_PARAM.PARAM_ID IS '参数ID';
COMMENT ON COLUMN T_STOCK_SYS_PARAM.PARAM_NAME IS '参数名称';
COMMENT ON COLUMN T_STOCK_SYS_PARAM.PARAM_VALUE IS '参数数值';































